### ISSUE TITLE
add-paths configuration needs policy

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#106]
Add-paths policy has become a more generally available feature.
The openconfig model has an "eligible-prefix-policy" for comparison purposes.

**Comment by suehares** [comment]
Adding this to route policy is useful.

**Comment by jhaas-pfrc** [comment]
I'm not sure what I was thinking at the time I opened this.  eligible-prefix-policy should do what we're interested in as the generic feature.

What I may have been thinking is that the policy language extensions may have been in need of a feature to limit path count for matching policy as an action in the grammar.  That is a feature Juniper has, however it doesn't seem to be more general at this time.

Closing issue for now.
