### ISSUE TITLE
valid-route not right semantic

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#122]
The following two leaves should be labeled "eligible" rather than "valid" to capture right semantics.

    leaf valid-route {
      type boolean;
      description
        "Indicates that the route is considered valid by the
         local router";
    }
    leaf invalid-reason {
      type identityref {
        base invalid-route-reason;
      }

**Comment by mjethanandani** [comment]
@jhaas-pfrc, apparently, you are missing a semicolon here 

../bin/submodules/ietf-bgp-rib-tables@2021-06-27.yang:90: error: unterminated statement definition for keyword "description", looking at r

which is causing other compilation failures.

../bin/submodules/ietf-bgp-rib@2021-06-27.yang:405: error: grouping "ipv4-loc-rib" not found in module "ietf-bgp-rib"
../bin/submodules/ietf-bgp-rib@2021-06-27.yang:406: error: grouping "ipv4-adj-rib" not found in module "ietf-bgp-rib"
../bin/submodules/ietf-bgp-rib@2021-06-27.yang:416: error: grouping "ipv6-loc-rib" not found in module "ietf-bgp-rib"
../bin/submodules/ietf-bgp-rib@2021-06-27.yang:417: error: grouping "ipv6-adj-rib" not found in module "ietf-bgp-rib"
../bin/ietf-bgp@2021-06-27.yang failed pyang validation
