### ISSUE TITLE
Temporarily work around RFC 9127 issues at IANA

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#142]
IANA has corrupt RFC 9127 bfd modules that is causing pyang to fail.
Temporarily remove those files in the build.  Currently older bfd modules are being pulled in a separate dependency part of the build that will satisfy work in progress.

When IANA has fixed the issue, roll this back and remove the bfd draft from the dependency script.

**Comment by jhaas-pfrc** [comment]
IANA has fixed the files as of December 30.  The fix is no longer needed.

**Comment by mjethanandani** [comment]
Does it mean we can withdraw the fix in the code to remove the BFD files from yang-parameters?

**Comment by jhaas-pfrc** [comment]
> Does it mean we can withdraw the fix in the code to remove the BFD files from yang-parameters?

Correct.
