### ISSUE TITLE
Mismatch of default "enabled" configuration for graceful restart and other inconsistencies

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#149]
grouping graceful-restart-config has an enabled leaf of type boolean with no default.

grouping mp-afi-safi-graceful-restart-config has an enabled leaf of type boolean with a default of "false".

Should the top level grouping have a similar default of false?

Should we permit configuration of the afi-safi entry to true when the top level config is false?  i.e. do we need a must clause?

**Comment by mjethanandani** [comment]
> grouping graceful-restart-config has an enabled leaf of type boolean with no default.

added a default of false.

> 
> grouping mp-afi-safi-graceful-restart-config has an enabled leaf of type boolean with a default of "false".
> 
> Should the top level grouping have a similar default of false?

The global level config uses graceful-restart-config grouping, and with the addition of default flag, will have it.

> 
> Should we permit configuration of the afi-safi entry to true when the top level config is false? i.e. do we need a must clause?

Agree. Will add a must clause to make sure that the enabled flag for aft/safi level config of graceful-restart is not different from the global level configuration.
