### ISSUE TITLE
Enhance policy part of the model

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#168]
This from @jhaas-pfrc:

What is the list of core policy operations we want to support?

Here's the start of a list.

match on afi/safi
Prefix matching.  Do we support exact only as opposed to range?  (junos e.g. prefix-list vs. route-filter)  Do we care about wildcard mask matches?
set localpref.  Match localpref (range?)
set med. set med + aigp?  set med + igp?  Match med (range?)
match on as-path regex (whose regex?)
match on community regex (whose regex?)
match on community using set algebra (whose semantics?  intersect? wholly contained?0
as-path prepend
community manipulate (all types) - add, delete, (re)set
match/set origin
match community-count
match neighbor? (ingress only?)
set next-hop

Policy for route flap damping?

**Comment by mjethanandani** [comment]
Hi @jhaas-pfrc,

> match on afi/safi 

I believe this is already supported under neighbors->neighbor->afi-safis->afi-safi->apply-policy->import-policy

**Comment by mjethanandani** [comment]
Hi @jhaas-pfrc,

> set next-hop

Did you mean match next-hop or set next-hop? Either ways, I have added support for match next-hop for now. See PR#170.

**Comment by jhaas-pfrc** [comment]
The list in email was constructed as the requirements rather than the todo list.
I think afi-safi is covered in the "afi-safi-in" element.

**Comment by keyur-arrcus** [comment]
Can we keep the regex related commands, community manipulate and aigp commands out for now? We will need a generic regex container to be defined for getting regex related commands. Also AIGP came a bit later on so won't fit into base model if you ask me.

**Comment by mjethanandani** [comment]
I have done an analysis of the list that @jhaas-pfrc, put together as part of this issue. With the combination of the two PRs that are currently under review, @keyur-arrcus, question about what he thinks should be addressed, I believe the only thing we are missing is 'match neighbor'. I will initiate a PR for that.

If we agree, then I can close this issue once the two PRs have been approved.

**Comment by jhaas-pfrc** [comment]
I think it's irresponsible to leave out community and as-path matching as they're two fundamental bits of things we need.

I agree deciding what to do about regex will take a bit of thinking.
Community matching may not only use regex but also community boolean algebra that's common in most implementations.

**Comment by mjethanandani** [comment]
> I think it's irresponsible to leave out community and as-path matching as they're two fundamental bits of things we need.

But we do support match-community-set and match-as-path-set already. Am I missing something?
