### ISSUE TITLE
BGP Auto-discovery 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#177]
BGP autodiscovery can use other protocols to dynamically configure BGP

1)  Juniper configuration: 

dynamic neighbor is done via ndp for IPv6

neighbor soft-reconfiguration router configuration command)
set protocols bgp group autodisc multipath multiple-as
set protocols bgp group autodisc dynamic-neighbor ndp peer-auto-discovery family inet6 ipv6-n
set protocols bgp group autodisc peer-as-list a-list
set protocols bgp group to-leaf-v4 family inet unicast extended-nexthop

        dynamic-neighbor ndp {
            peer-auto-discovery {
                family inet6 {
                    ipv6-nd;
                }
                interface tor-to-leaf;
            }

I do not see how this can be configured with the current  mib. 

2) Cisco does not seem to support this feature, but I may have missed it.

**Comment by mjethanandani** [comment]
Not a standard feature.
