### ISSUE TITLE
VPLS BGP auto-discovery - In or Out of basic BGP? 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#178]
2) L2vpn auto-discovery-only  - 

set protocols bgp group pe-pe type internal
set protocols bgp group pe-pe connect-retry-interval 1
set protocols bgp group pe-pe family l2vpn auto-discovery-only
set protocols bgp group pe-pe family l2vpn signaling
set protocols bgp group pe-pe neighbor 192.0.2.3
set protocols bgp group pe-pe neighbor 192.0.2.4

Manuals: 
https://www.cisco.com/c/en/us/td/docs/ios/12_2sr/12_2srb/feature/guide/fs_vpls.html

https://www.juniper.net/documentation/us/en/software/junos/vpn-l2/topics/example/vpls-bgp-ldp-autodiscovery-mesh-group.html

**Comment by mjethanandani** [comment]
Would this be something a core BGP model would need to support, or would this be an augmentation of the model by a L2VPN model?

**Comment by mjethanandani** [comment]
Does not belong in this model. Should be supported by a L2VPN or VPLS YANG model draft.
