### ISSUE TITLE
BGP neighbor IP address "fall-over bfd"  - Is this covered? 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#179]
Juniper: 
set logical-systems A protocols bgp group internal-peers bfd-liveness-detection minimum-interval 1000
bfd-liveness-detection {
    detection-time {
        threshold milliseconds;
    }
    minimum-interval milliseconds;
    minimum-receive-interval milliseconds;
    multiplier number;
    no-adaptation;
    transmit-interval {
        minimum-interval milliseconds;
        threshold milliseconds;
    }
    version (1 | automatic);
}
Cisco: 
Router(config-if)# bfd interval 50 min_rx 50 multiplier 5
router bgp autonomous-system-number
neighbor ip-address fall-over bfd
end

**Comment by mjethanandani** [comment]
I do not believe we support this currently.

**Comment by jhaas-pfrc** [comment]
In the case of the Juniper behavior, we support bfd already in the yang module's bfd stanza.
I'm not clear what the cisco behavior is intended to be, if anything different.
@suehares would you please post a pointer to the specific web page to this?

**Comment by suehares** [comment]
I believe that for cisco the BFD failover is a link function. 
I do not know if  "show BGP neighbors details"
links to the BFD informatioin for a BGP interface. 

In any case, the appropriate place for the failover information storage is the BFD module.
