### ISSUE TITLE
Support for All types of Box Resets - work in progress 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#180]
I'm still trying to track down all the different types of Resets to see if the Cisco, Juniper, Huawei, and FR-routing are supported. 

Code from the yang module - I'm looking at 
       |  +---x clear {bt:clear-neighbors}?
       |     +---w input
       |     |  +---w (operation)?
       |     |  |  +--:(operation-admin)
       |     |  |  |  +---w admin?          empty
       |     |  |  +--:(operation-hard)
       |     |  |  |  +---w hard?           empty
       |     |  |  +--:(operation-soft)
       |     |  |  |  +---w soft?           empty
       |     |  |  +--:(operation-soft-inbound)
       |     |  |     +---w soft-inbound?   empty {bt:route-refresh}?
       |     |  +---w clear-at?             yang:date-and-time
       |     +--ro output
       |        +--ro clear-finished-at?   yang:date-and-time

Keyur and Jeff may be able to check this quickly and post 

I will not finish this until Tuesday.

**Comment by mjethanandani** [comment]
The fundamental clear commands are covered.
