### ISSUE TITLE
Removing one's own AS from AS-Path-Prepend 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#181]
Can this yang support: 

Juniper: 
as-path-prepend {
        local-as 200 no-prepend-global-as;
        neighbor 10.1.1.1;
}		

Are you using the following: 
		
    leaf remove-private-as {
      type bt:remove-private-as-option;
      description
        "When this leaf is specified, remove private AS numbers from
         updates sent to peers.";
    }

If so what is the configuration format?  

I could not find an example of this feature. 

https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/autonomous-systems.html

**Comment by mjethanandani** [comment]
Look at these options:

```
       |     +--rw as-path-options
       |     |  +--rw allow-own-as?      uint8
       |     |  +--rw replace-peer-as?   boolean
```

**Comment by mjethanandani** [comment]
Juniper specific. Not a standard feature.
