### ISSUE TITLE
Route Selection Options 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#182]
This thread looks at the combination of route select 
       |  +--rw route-selection-options
       |  |  +--rw always-compare-med?           boolean
       |  |  +--rw ignore-as-path-length?        boolean
       |  |  +--rw external-compare-router-id?   boolean
       |  |  +--rw advertise-inactive-routes?    boolean
       |  |  +--rw enable-aigp?                  boolean
       |  |  +--rw ignore-next-hop-igp-metric?   boolean

To see if these are complete. 

What I do not see is: 

a) Adding IGP cost to MED (med-plus-igp)
b) applying Cisco IOS nondeterministic behavior (cisco-non-deterministic) 
c) igp-multiplier
d) med-multiplier 

Example configuration 
path-selection {
(always-compare-med |  cisco-non-deterministic | external-router-id);
as-path-ignore;
l2vpn-use-bgp-rules;
med-plus-igp {
igp-multiplier number;
med-multiplier number;
}

Note the l2vpn-use-bgp-rules - may be out of scope, but we should know how to add it.

**Comment by suehares** [comment]
**Juniper: 
BGP Table path selection** 
https://www.juniper.net/documentation/en_US/junos/topics/reference/general/routing-protocols-address-representation.html

The following parameters are followed for BGP's path selection:

Prefer the highest local-preference value.
Prefer the shortest AS-path length.
Prefer the lowest origin value.
Prefer the lowest MED value.
Prefer routes learned from an EBGP peer over an IBGP peer.
Prefer best exit from AS.
For EBGP-received routes, prefer the current active route.
Prefer routes from the peer with the lowest Router ID.
Prefer paths with the shortest cluster length.
Prefer routes from the peer with the lowest peer IP address. Steps 2, 6 and 12 are the RPD criteria.

**Comment by suehares** [comment]
**Cisco order** 

- https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/13753-25.html


Cisco order 

1.  weight
2. highest Local-pref
3. locally originated 

3a) Prefer the path that was locally originated via a network or aggregate BGP subcommand or through redistribution from an IGP.
3b) AIGP -  If AIGP is configured AND the [bgp bestpath aigp ignore ]  
3c) Just [bgp bestpath aigp ignore ] - skips this step 

4.  Shortest AS-Path
5.  Lowest origin types (IGP, EGP, incomplete) 
6.  Prefer the path with the lowest [multi-exit discriminator (MED)]
6a) If [bgp always-compare-med ] 
6b) If [bgp bestpath med-confed ] 
6c) if [bgp bestpath med missing-as-worst ]

7) Prefer eBGP over iBGP paths.
If bestpath is selected, go to Step 9 (multipath).

8) Prefer the path with the lowest IGP metric to the BGP next hop.
9) Determine if multiple paths require installation in the routing table for [BGP Multipath] 
Continue, if bestpath is not yet selected.

10) When both paths are external, prefer the path that was received first (the oldest one).
skip this step if any of the following is true
-  [bgp best path compare-routerid] enabled
- The router ID is the same for multiple paths because the routes were received from the same router.
-  the current best path can be lost when, for example, the neighbor that offers the path goes down.

11) Prefer the route that comes from the BGP router with the lowest router ID.

12) Prefer paths with shortest cluster list length 

13) Prefer routes from the peer with the lowest peer IP address

**Comment by mjethanandani** [comment]
> What I do not see is:
> 
> a) Adding IGP cost to MED (med-plus-igp)

Should be added. A boolean flag.

> b) applying Cisco IOS nondeterministic behavior (cisco-non-deterministic) c) igp-multiplier d) med-multiplier

Vendor specific.

> 
> Example configuration path-selection { (always-compare-med | cisco-non-deterministic | external-router-id); as-path-ignore; l2vpn-use-bgp-rules; med-plus-igp { igp-multiplier number; med-multiplier number; }
> 
> Note the l2vpn-use-bgp-rules - may be out of scope, but we should know how to add it.

**Comment by suehares** [comment]
Need to add bestpath container

**Comment by mjethanandani** [comment]
Best path option should be implemented, with the min of a container of where it goes. Needs to be finalized before shipping this draft.

**Comment by keyur-arrcus** [comment]
> 

@suehares : The Cisco-non-deterministic options could be a vendor specific augmentation right?

**Comment by mjethanandani** [comment]
This should be evaluated in light of Pull Request #197

**Comment by jhaas-pfrc** [comment]
> This should be evaluated in light of Pull Request #197

I agree with Mahesh, I believe that we've now got this covered.
We discussed and will not be implementing the cisco-non-deterministic leaf in the IETF yang module since it's not a standardized nor pervasive behavior.
We'll close this issue for now. Please re-open should you not concur.
