### ISSUE TITLE
Need an example of Communities in Appendix 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#183]
7)  Communities - etended 

From BGP 
+--rw-neighbors
|  +rw neighbor* [remote-address]
|  |  ...
|  |  +--rw send-community*              identityref
|  |    (bt:send-communities}?
|  | 

      <send-community>bt:standard</send-community>
            <send-community>bt:large</send-community>

**Comment by mjethanandani** [comment]
Did you mean an example for ext-community-set?

**Comment by mjethanandani** [comment]
BGP policy example covers communities.
