### ISSUE TITLE
Active Route - 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#192]
How do you link the BGP show commands to an active route in the FIB? 
Is cisco using "best" for active?   

Juniper: 
[Some people ]
(https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/command/show-route-detail.html)
state - State of the route (a route can be in more than one state). See Table 3.
   not seeing where active is coded or linked to 
 
**Device# show ip bgp ipv4 unicast 150.1.1.0**

BGP routing table entry for 150.1.1.0/24, version 2
Paths: (1 available, best #1, table default)
  Not advertised to any peer
  Refresh Epoch 1
  65002, imported path from 1:1:150.1.1.0/24 (vpn1)
    4.4.4.4 (metric 11) from 4.4.4.4 (4.4.4.4)
      Origin IGP, metric 0, localpref 100, valid, internal, best
      Extended Community: RT:1:1
      mpls labels in/out nolabel/16

**Cisco:** 
 Status codess—The table entry is suppressed.
*—The table entry is valid.
>—The table entry is the best entry to use for that network.
i—The table entry was learned via an internal BGP (iBGP) session.

**Comment by suehares** [comment]
There is no "active route" in the RIB in the IETF RIB module.

**Comment by suehares** [comment]
RIB-in-Post - is what is present in LOC-RIB for BGP

**Comment by suehares** [comment]
Just mention this missing at IETF presentation.

**Comment by jhaas-pfrc** [comment]
The idea of an active route is a concept for the Routing Table, not the BGP RIBs.  The appropriate place for the Routing Table is a project in netmod similar to the routing-cfg module.  The idea of a central Routing Table was broached several times over the years in netmod in response to that routing-cfg work.

At this time, netmod doesn't have that work chartered.
