### ISSUE TITLE
next-hop policy in BGP - Can you set the next-hops via policy 

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#194]
Can we handle all of these types:  
1) set next-hop -  [Sue: Think you can do it, but not able to put together how; Good for example]
 2) set no-nexthop-change (J),  [Sue - not sure you can do this] 
 3) set next-hop self (J, H, H),   [Sue: Can do] 
 4) set no-next-hop-self (J),    [Sue: Not sure you can do this] 
 5) set next-hop-local (H)       [Sue: Not sure how this is done.  Thought we agreed it could be]
 6)nexthop recursive-lookup  [Sue: Not sure how this is identified or done]

-------------------
**model text:**
```
container next-hop-sets {
           description
             "Definition of a list of IPv4 or IPv6 next-hops which can
              be matched in a routing policy.";
           list next-hop-set {
             key "name";
             description
               "List of defined next-hop sets for use in policies.";
             leaf name {
               type string;
               mandatory true;
               description
                 "Name of the next-hop set.";
             }
             leaf-list next-hop {
               type bgp-next-hop-type;
               description
                 "List of IP addresses in the next-hop set.";
              }
           }
         }
       }

     typedef bgp-next-hop-type {
       type union {
         type inet:ip-address-no-zone;
         type enumeration {
           enum self {
             description
               "Special designation for local router's own
                address, i.e., next-hop-self.";
           }
         }
       }

```
How does this model allow: 
Juniper command: 
no-nexthop-change (BGP multihop)
no-nexthop-self  

**Cisco**: 
enable
configure terminal
router bgp as-number
address-family {ipv4 | ipv6 | l2vpn | nsap | rtfilter | vpnv4 | vpnv6 }
neighbor ip-address remote-as as-number
neighbor ip-address activate
neighbor ip-address ebgp-multihop ttl
neighbor ip-address next-hop-unchanged
end
show ip bgp

**Huawei:**
Run nexthop recursive-lookup { route-policy route-policy-name | route-filter route-filter-name }
BGP next hop iteration based on a route-policy or route-filter is configured.

nexthop recursive-lookup route-policy route-policy-name
Run peer { ipv6-address | group-name } next-hop-local

**Comment by keyur-arrcus** [comment]
@mjethanandani: These are pretty easy to add.

**Comment by mjethanandani** [comment]
Agreed to implement:

- set-nexthop-self (item 3)
- verify that set-nexhop-local (item 5) is the same as set-nexthop-self

Separate item 2 and 4 into a separate issue for BGP multi hop, supported by Cisco and Juniper.

Item 6 should be left out as vendor specific.

**Comment by mjethanandani** [comment]
With the last two open issues moved out, this can be closed.
