### ISSUE TITLE
     grouping bgp-adj-rib-in-post-route-annotations-state  - correction

### ISSUE THREAD

**Issue by suehares** [mjethanandani/ietf-bgp-yang#195]
grouping bgp-adj-rib-in-post-route-annotations-state {
       description
         "Data definitions for information attached to routes in the
          Adj-RIB-in post-policy table";
       leaf best-path {
         type boolean;
         description
           "Current path was selected as the best path.
             Best path should indicate that the route is present in BGP LOC-RIB. ";
       }
     }

**Comment by mjethanandani** [comment]
Hi @suehares, could you explain what is the change you are looking at, or better still provide a PR with the change?

**Comment by keyur-arrcus** [comment]
@suehares: This is a post policy state on a per path basis. Boolean is to indicate if the path is a best path or not. While we are at it, imho we should add similar state to show if the path is a backup path and/or multi path.
