### ISSUE TITLE
TCP MSS and PMTUD

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#221]
The TCP YANG model defines TCP MSS and PMTUD from a state perspective. Applications like BGP need to be able to configure the leafs to indicate their preference.

**Comment by mjethanandani** [comment]
Need to leave the two leafs in this module for config purposes, and use tcp:mss typedef for mss config.

**Comment by jhaas-pfrc** [comment]
Closed via request #223
