### ISSUE TITLE
set-ext-community currently only does ietf-rt-types extended communities

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#232]
container set-ext-community {
           description
             "Action to set the extended community attributes of the
              route, along with options to modify how the community is
              modified. Extended communities may be set using an inline
              list OR a reference to an existing defined set (but not
              both).";

  [...]
             case inline {
               leaf-list communities {
                 type rt-types:route-target;
                 description
                   "Set the extended community values for the update
                    inline with a list.";
               }

In the above set operation, we can only set route-target types from RFC 8294.  This isn't general enough for BGP.  Also, RFC 8294 has IANA maintenance considerations.

**Comment by mjethanandani** [comment]
@jhaas-pfrc, I am trying to remember what was our resolution going to be for this issue.

Do we use our own definition of bgp-ext-community-type that does not carry the prefix of 6: (as that is not in the IANA registry)?

I know were you going to write to Yingzhen and/or create an errata for RFC 8294 to highlight that the definition for route-target in the model is incorrect. Also from a maintainability perspective, should this be an IANA module? But that is not happening anytime soon, and we do not want our model to be gated on this change.
