### ISSUE TITLE
route-reflector/no-client-reflect depends on route-reflector/client

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#242]
The structure of no-client-reflect has it as a peer-node with client.  Typically implementations will make no-client-reflect a child of the client node.

A few thoughts:
Option 1: Restructure client into a container rather than a leaf, and make it presence?  This would let us make no-client-reflect live in the hierarchy appropriately.
Option 2: Create a "must" dependency between the two leaves.

**Comment by jhaas-pfrc** [comment]
The Cisco configuration for this isn't strongly coupled:
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-16/irg-xe-16-book/configuring-internal-bgp-features.html
"no bgp client-to-client reflection"

**Comment by jhaas-pfrc** [comment]
The Juniper configuration:
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/no-client-reflect-edit-protocols-bgp.html
Contrary to my initial issue text, this is per-neighbor or similar scope rather than client scoped.

**Comment by jhaas-pfrc** [comment]
Related Juniper client configuration is done based on the neighbors being in a scope that has a cluster-id configured.
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/bgp-rr.html

**Comment by jhaas-pfrc** [comment]
The Huawei configuration has route reflection configured per-group, per afi-safi.  It also has the equivalent of no-client reflect scoped per afi-safi.
https://support.huawei.com/enterprise/en/doc/EDOC1100138140/e3f164dc/example-for-configuring-a-bgp-route-reflector

**Comment by jhaas-pfrc** [comment]
Nokia's configuration is similar to juniper's in that it configures route reflector clients by putting them in a group with a cluster-id.  I don't see an equivalent of "no-client-reflect".
https://infocenter.nokia.com/public/7750SR222R1A/index.jsp?topic=%2Fcom.nokia.Unicast_Guide%2Fbgp_router_refl-ai9exj5yk8.html

**Comment by jhaas-pfrc** [comment]
Arista configures no-client reflect (no bgp client-to-client reflection) at global scope.
neighbors are made route reflector clients by neighbor configuration.

https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp#xx1116343

**Comment by jhaas-pfrc** [comment]
Openconfig doesn't have a no-client-reflect... likely because of the above.

**Comment by jhaas-pfrc** [comment]
My conclusion upon looking at the likely modeling for no-client-reflect with the varying options above is we'd end up with three features that end up being non-exclusive.  This will make implementations go through more complexity than they should.

For now, let's remove no-client-reflect.  Each vendor will need to augment in at the appropriate hierarchy for their implementation.

**Comment by mjethanandani** [comment]
Reading up more on the issue, the Arista models seems simple enough to add, leaving enough room for each vendor to fine tune it more if necessary. And this could be done with a feature statement.

But I am not a BGP expert to know what repercussions there would be.

**Comment by suehares** [comment]
How does thie approach for the no client reflect work per AFI/SAFI?  (Huawei).  

This ability to turn on/off client reflection per AFI/SAFI seems to group in importance as we head into VPN (EVPN, MVPN), and SR routing.  If we decide to remove hte "no-client reflect", I think we will be adding this back in with the other features.  

I would like to chat about this more with Keyur's and Jie's input.  I have not seen these two post.

**Comment by keyur-arrcus** [comment]
My suggestion is that we leave this at AFI/SAFI level where it makes more sense. Implementations can deviate as and how they want.

**Comment by jhaas-pfrc** [comment]
As noted in prior verbal conversation, in some deployments it makes sense for the group of routers.  Opinions about how much this is interesting on a per-afi-safi basis for a given set of routers that you are (or are not) doing client reflection are varied. :-)

Note that the current code as of the time of this comment has it present as a group/neighbor option.

**Comment by suehares** [comment]
Jeff: 

I agree that in some deployments it makes sense for the group of routers.  I was not advocating removing the group/neighbor option.  This option is valuable.  However, I think that AFI/SAFI has relevance as well. 

What I'm wondering (naively perhaps) is whether linking "reflector/no-client reflector" to AFI/SAFI should be added in addition to groups/neighors.  The inheritance could thing fill in groups under an AFI/SAFI.

**Comment by jhaas-pfrc** [comment]
> Jeff:
> 
> I agree that in some deployments it makes sense for the group of routers. I was not advocating removing the group/neighbor option. This option is valuable. However, I think that AFI/SAFI has relevance as well.
> 
> What I'm wondering (naively perhaps) is whether linking "reflector/no-client reflector" to AFI/SAFI should be added in addition to groups/neighors. The inheritance could thing fill in groups under an AFI/SAFI.

As replied to Mahesh earlier... post a diff. :-)  My concern remains that the combination of if-feature to support known implementations of the feature may be daunting.  I'd be happy to be proven wrong.

**Comment by mjethanandani** [comment]
> Related Juniper client configuration is done based on the neighbors being in a scope that has a cluster-id configured.
> https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/topic-map/bgp-rr.html

Not clear on why a cluster-id needs to be configured. Can a neighbor be a route reflector without having a cluster-id?

Ignore my previous comment on Arista config, in general agree with Option 1, i.e. make client a presence container on a per-neighbor level, add cluster-id and no-route-reflect as leafs in the container. Configuration of either the cluster-id or no-route-reflect enables the feature.

**Comment by jhaas-pfrc** [comment]
The cluster-id is the relevant bit of configuration state that is required to be a route-reflector.  Some implementations may be satisfied in saying they're a route-reflector (boolean state) and perhaps have their cluster-id default to the router-id.

Juniper's implementation requires cluster to be set in order to do route reflection.  no-client-reflect isn't made a dependent attribute of that behavior, but I think that's for historical reasons.
