### ISSUE TITLE
Fix example a.1.2

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#267]
libyang err : Invalid identityref "tcp:aes-128
      " value - identity not found in module "ietf-tcp". (Schema location "/ietf-key-chain:key-chains/key-chain/key/crypto-algorithm", data location "/ietf-key-chain:key[key-id='55']", line number 22.)
YANGLINT[E]: Failed to parse input data file "yang/example-bgp-configuration-a.1.2.xml".
failed (error code: 0)

**Comment by jhaas-pfrc** [comment]
Note that my pull request for #257 will cause a conflict here.

**Comment by mjethanandani** [comment]
Do not worry. I will handle the conflict when it arrives.
