### ISSUE TITLE
Reconcile prefix-limit vs. OC model

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#307]
The IETF model started from OC.  OC has since changed the semantics of their prefix-limit behaviors in the prefix-limit container.  Similarly, there's a neighbor leaf last-prefix-limit-exceeded that provides information about when things last reset.

Review both sets of semantics against implementations and reconcile them.

**Comment by jhaas-pfrc** [comment]
Partially addresses Issue #292

**Comment by jhaas-pfrc** [comment]
The Juniper feature is here:
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/prefix-limit-edit-protocols-bgp.html

The "teardown" option is what controls whether the session gets torn down when the limit is exceeded.  teardown includes a percentage option that is the warning threshold.

The idletimeout feature accepts a time in _MINUTES_, but also has the option for "forever".

There is also support for "drop-excess" and "hide-excess" which isn't covered in the IETF model.

Note that Juniper also supports an "accepted-prefix-limit" feature distinct from the prefix-limit feature.

**Comment by suehares** [comment]
For my information: 
1) Is OC - claiming prefix limits at full box, AFI/SAFI, groups, and neighbors? 
2) Is it inbound/outbound or both? 

References would be helpful as you review it.  
Thanks Sue

**Comment by jhaas-pfrc** [comment]
For one flavor of Cisco:
https://www.cisco.com/c/en/us/support/docs/ip/border-gateway-protocol-bgp/25160-bgp-maximum-prefix.html

Prefix-limit is per neighbor:
neighbor {ip-address | peer-group-name} maximum-prefix 
maximum [threshold] [restart restart-interval] [warning-only]

**Comment by jhaas-pfrc** [comment]
Arista is considering outbound prefix-limits.
https://aristanetworks.force.com/AristaCommunity/s/question/0D52I00007ERqC1SAL/bgp-outbound-prefix-limit

**Comment by jhaas-pfrc** [comment]
Arista supports a neighbor maximum-paths command. This seems to be warning only?
https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp

**Comment by jhaas-pfrc** [comment]
Huawei supports 
https://support.huawei.com/enterprise/en/doc/EDOC1100064351/2456e6b0/peer-route-limit

peer { group-name | ipv4-address | ipv6-address } route-limit limit [ percentage ] [ alert-only | idle-forever | idle-timeout times ]

**Comment by keyur-arrcus** [comment]
I am confused.  Maximum path support of Arista is different from prefix limit. Furthermore, your right that this command is going to have variations across implementations.IMHO we should consider a common set in the base model. More advance config options can be implemented as part of deviation?

**Comment by jhaas-pfrc** [comment]
@keyur-arrcus 
> I am confused. Maximum path support of Arista is different from prefix limit. Furthermore, your right that this command is going to have variations across implementations.IMHO we should consider a common set in the base model. More advance config options can be implemented as part of deviation?

Feel free to paste the appropriate citation to the relevant feature.  These issues are usually getting 3 minutes of Google search results as my "research".

If you think that the proposed diff doesn't match "common set", make comments in the diff.
