### ISSUE TITLE
Name normalization introduced xml warnings for too long lines.

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#313]
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1167), 1 characters longer than 72 characters: 
             "RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 4.2,
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1168), 2 characters longer than 72 characters: 
              RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 10.";
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1184), 1 characters longer than 72 characters: 
             "RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 4.2,
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1185), 2 characters longer than 72 characters: 
              RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 10.";
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1193), 1 characters longer than 72 characters: 
             "When used as a configuration (rw) value, this Time interval
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1194), 2 characters longer than 72 characters: 
              (in seconds) for the KeepAlive timer configured for this BGP
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1195), 2 characters longer than 72 characters: 
              speaker with this peer.  A reasonable maximum value for this
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1199), 1 characters longer than 72 characters: 
              value, operationally it SHOULD have a value of one-third of
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1209), 1 characters longer than 72 characters: 
             "RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 4.4,
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1210), 2 characters longer than 72 characters: 
              RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 10.";
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1218), 1 characters longer than 72 characters: 
             "Time interval (in seconds) for the MinASOriginationInterval
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1223), 2 characters longer than 72 characters: 
              RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 10.";
/app/draft/draft-ietf-idr-bgp-model-16.xml(799): Warning: Too long line found (L1247), 2 characters longer than 72 characters: 
              RFC 4271: A Border Gateway Protocol 4 (BGP-4), Section 10.";

**Comment by jhaas-pfrc** [comment]
@mjethanandani I think you introduced these when updating all of the references.  Yes, this is on v16.  Fix is to split lines.

**Comment by mjethanandani** [comment]
I am not seeing these errors in my setup. Moreover, all these lines are no more than 69 columns wide. So I am not sure why it should be complaining about exceeding 72 col width.

**Comment by jhaas-pfrc** [comment]
On latest v16, I'm not seeing this.  Not sure where the transient issue was introduced.
Closing issue.
