### ISSUE TITLE
AS path sets

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#34]
The current definition of AS path sets in a container by the name as-path-sets defines it as a list of as-path-set-name which is of type string and of a leaf-list of as-path-set-member which is also a string. This is way too generic. For example, is this for a prepend? A specific match?  A regex?  Different containers should be defined for those cases.

Need to tie this with the routing policy module. Discuss with Acee.

**Comment by mjethanandani** [comment]
Per Jeff, this can be closed after the TODO comment is removed in the model.

**Comment by suehares** [comment]
How does this interact with AS-Path reg-ex?

**Comment by jhaas-pfrc** [comment]
Closing this one in favor of issue #228
