### ISSUE TITLE
Make prefixes consistent between definition and use

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#344]
Current prefixes defined in the models need to be consistent with where they are imported and used.

For example if iana-bgp-types has a prefix of bt, then modules importing it should also use bt as a prefix.

**Comment by mjethanandani** [comment]
For now just make the prefix consistent between its definition and its use in models.

**Comment by mjethanandani** [comment]
name: iana-bgp-types
namespace: urn:ietf:params:xml:ns:yang:iana-bgp-types
prefix: bt
reference: RFC XXXX

name: iana-bgp-community-types
namespace: urn:ietf:params:xml:ns:yang:iana-bgp-community-types
prefix: bt
reference: RFC XXXX

**Comment by suehares** [comment]
5.2 section in text for above in -16.
