### ISSUE TITLE
How is AS path length calculated?

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#35]
The current definition for as-path-length in the BGP policy module does not define how the AS path length is calculated. Is it total count of ASes in the path, or the calculated length per BGP rules? There are probably different use cases for each. Also add the comparison operators that OpenConfig has defined.

Discuss with OpenConfig.

**Comment by mjethanandani** [comment]
It was agreed in the WG meeting 106 that AS path length will be calculated. Also that no comparison operator needs to be defined.

**Comment by jhaas-pfrc** [comment]
In reviewing this, I still don't have an answer that would be great for the model.  The Juniper implementation doesn't currently have CLI to do this comparison.  I'd probably choose to use the value calculated by BGP effective path length rules, which would do things like treat an AS-set of length < 255 as contributing 1 to the length.

The following Cisco feature is what seems to be desired.  We need an answer from Cisco or similar vendors:
https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-0/routing/command/reference/rr40crs1book_chapter8.html#wp716406270

**Comment by suehares** [comment]
Does ignore as-path length get added here or in the "undefined" extension set.

**Comment by jhaas-pfrc** [comment]
Per discussion, we'll make this the bgp length comparison rules from the rfc.

**Comment by jhaas-pfrc** [comment]
Resolved in #43
