### ISSUE TITLE
List of AS path segments

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#36]
When working in transitional mode, we really have received as-path, received as4-path and calculated as-path (4byte). 

Need to discuss on IDR mailing list.

**Comment by mjethanandani** [comment]
Document in the (YANG model?) that AS_PATH is always 4-bytes.

**Comment by jhaas-pfrc** [comment]
The current as-path and as4-path containers and their documentation addresses this consideration.  However, review has shown that we're not quite doing this right for as4-aggregator.  Closing this issue and opening a new one.
