### ISSUE TITLE
Should as-path-segment-type be a enum maintained by IANA

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#49]
This is being suggested so that it can be updated (without updating this draft), although it is not clear how models can get updated without touching the draft. 

Another way to deal with this is to keep it as an identity but make it a union with uint8. That will allow a new segment type to be used without an implementation barfing on a type that has not been defined as an identity.

**Comment by jhaas-pfrc** [comment]
Even with potential deprecation of as-set types (as-set/confed-as-set), these values are likely to stay stable in BGP for years.  I suggest just leaving them in their current form.
