### ISSUE TITLE
Regular expressions for bgp-community-regexp-type.

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#53]
Needs more work to decide what format bgp-community-regexp-type regexps can take.

**Comment by jhaas-pfrc** [comment]
Citation for POSIX regular expressions:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html

**Comment by jhaas-pfrc** [comment]
Cisco IOS-XR regular expressions.  Includes support for backreferences, and a number of other convenience shortcuts.  Does not support character classes.
https://www.cisco.com/c/en/us/td/docs/routers/xr12000/software/xr12k_r4-1/getting_started/configuration/guide/gs41xr12k/gs41aexp.html#wp1013665

**Comment by jhaas-pfrc** [comment]
Juniper's support.  
https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/concept/policy-defining-bgp-communities-and-extended-communities-for-use-in-routing-policy-match-conditions.html#understanding-how-to-define-bgp-communities-and-extended-communities__id-10223306

Excludes backreferences and character classes.  No other special shortcuts.

**Comment by jhaas-pfrc** [comment]
Arista supports regular expressions via "ip community-list regexp"
https://www.arista.com/en/um-eos/eos-border-gateway-protocol-bgp
The documentation for regular expressions seems to be here:
https://www.arista.com/en/um-eos/eos-command-line-interface-cli

It seems to be BRE without character classes, or backreferences.
AS Path regular expressions get the _ special meaning token, not relevant for communities.

**Comment by jhaas-pfrc** [comment]
Huawei seems to support community filtering via regex:
https://support.huawei.com/enterprise/en/doc/EDOC1000178171/45968338/configuring-a-community-filter

I'm not able to find a core reference for the syntax supported, but the general CLI version uses :
https://support.huawei.com/enterprise/en/doc/EDOC1000178166/f0a31a7b/filtering-output-information-based-on-the-regular-expression

The above is BRE without character classes or backreferences.
