### ISSUE TITLE
bgp-set-med-type

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/ietf-bgp-yang#61]
Acee (as a YANG doctor) commented:

20. Page 78, "bgp-set-med-type": Please describe the syntax of the pattern
      in the description.

to which Jeff commented:

Set med in implementations typically permits additive/subtractive MEDs.  This
permits operations such as "set med = med + 5".

Syntax issue: the implementation is typically "set med", "set med additive
<value>" or "set med-igp".  Thus the syntax that's additive is only
applicable in some of these cases.

I believe we'll hae to restructure this.

@jhaas-pfrc, how do you suggest that this be restructured?

**Comment by jhaas-pfrc** [comment]
I believe the current structure addresses the issue originally filed.
