### ISSUE TITLE
Should route-selection-options be per-group/neighbor or just global?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#62]
grouping route-selection-options is applied at multiple scopes.

Some of these options are reasonable per-peer:
- MED
- enable-aigp
- advertise-inactive

Some of these are likely intended to be consistent for the entire BGP implementation:
- always-compare-med
- ignore-as-path-length
- external-compare-router-id
- ignore-nexthop-igp-metric

The med feature governs both sending of MEDs and utliizing it, which might need to be distinct properties.

The general distinction of these two things is there's a cluster of items governing things we put into the protocol, while other govern how we handle them on receive for route-selection purposes.

I suspect these should be split.  I also suspect that the second cluster is likely only global-scoped.

**Comment by suehares** [comment]
Jeff: 

My understanding of the concepts behind these features is the same as yours. 
My earlier comments on these features was to write an IDR draft to have the IDR WG and GROW WG specifically look at these additional features. 

My current instinct is to put these in the model to the best our ability and then ask for time at Grow and IDR at IETF 111 to provide the details.  Also, to ask Grow for an interim after IETF 111 to specifically discuss the BGP model. 

We might get some feedback at that point.

**Comment by jhaas-pfrc** [comment]
After further review and looking at the openconfig module, these options are all appropriate for the global and per afi/safi configuration (for implementations that permit per-address family route selection behaviors).  They simply should not vary at the neighbor level.

The fix is to remove it from the neighbor configuration.
