### ISSUE TITLE
Clarify paths vs. prefixes?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#63]
End users often find the distinction between paths and prefixes to be confusing.  These terms don't clearly map to the protocol definition.  The word "route" is often overloaded and adds to the ambiguity.

I'd propose the following change:

  grouping state {
    description                                                                                              
      "Grouping containing common counters relating to prefixes and                                          
       paths";
    leaf total-paths {                                                                                       
      type uint32;
      config false;
      description
        "Total number of BGP paths (BGP Routes) within the context";                                                      
    }     
    leaf total-prefixes {
      type uint32; 
      config false;
      description
        "Total number of BGP prefixes (destinations) received within the context";

**Comment by suehares** [comment]
Agree this is an important textual change.
