### ISSUE TITLE
Update referenced to labeled unicast?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#64]
Our reference for labeled unicast stuff is the following:

"RFC 3107: Carrying Label Information in BGP-4.";  

Should we update this to RFC 8277?

**Comment by suehares** [comment]
As IETF WG chair, I would simply move this to RFC8277.  
However, do the vendors still support RFC3107.   Do we handle this by augmentation?

**Comment by jhaas-pfrc** [comment]
RFC 8277 was mostly about fixing things that never quite worked in RFC 3107.  The additional label capability, and clarifications about label stacks.

Since the reference we're updating is the anchor reference for the afi/safi rather than the label stuff and IANA has already moved the references to 8277, I'll just do a patch for that update.
