### ISSUE TITLE
peer-type enumeration needs confed work?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#67]
Since this is an enum, "confederation" is probably not sufficient.  It should likely be "confederation-internal/confederation/external".

  typedef peer-type {
    type enumeration {
      enum internal {
        description
          "Internal (IBGP) peer";
      }
      enum external {
        description
          "External (EBGP) peer";
      }
      enum confederation {
        description
          "Confederation as peer";
      }
    }
    description
      "Labels a peer or peer group as explicitly internal,
       external, or confederation.";
  }

**Comment by suehares** [comment]
agree with Jeff.

**Comment by mjethanandani** [comment]
> agree with Jeff.

Hi Sue, this is where you should go the PR (this link)[https://github.com/mjethanandani/ietf-bgp-yang/pull/104](url) and approve the PR
