### ISSUE TITLE
cluster-id when clause wrong?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#69]
Consider the following below.

Shouldn't the when clause for route-reflector-client-id be when true rather than false?

Similarly, shouldn't the no-client-reflect share the same condition?

  grouping structure-neighbor-group-route-reflector {
    description
      "Structural grouping used to include route reflector
       configuration and state for both BGP neighbors and peer
       groups";
    container route-reflector {
      description
        "Route reflector parameters for the BGP peer-group";
      reference
        "RFC 4456: BGP Route Reflection.";
      leaf route-reflector-cluster-id {
        when "../route-reflector-client = 'false'";
        type bt:rr-cluster-id-type;
        description
          "Route Reflector cluster id to use when local router is
           configured as a route reflector.  Commonly set at the
           group level, but allows a different cluster id to be set
           for each neighbor.";
        reference
          "RFC 4456: BGP Route Reflection: An Alternative to
                     Full Mesh.";
      }
      leaf no-client-reflect {
        type boolean;
        default "false";
        description
          "When set to 'true', this disables route redistribution
           by the Route Reflector. It is set 'true' when the client is
           fully meshed to prevent sending of redundant route
           advertisements.";
      }
      leaf route-reflector-client {
        type boolean;
        default "false";
        description
          "Configure the neighbor as a route reflector client.";
        reference
          "RFC 4456: BGP Route Reflection: An Alternative to
                     Full Mesh.";
      }
    }
  }

**Comment by suehares** [comment]
As I read the text, the 
when "../route-reflector-client = 'false'"; - because the node cannot be a route reflector and a client.

The inclusion on leaf no-client-reflect of: 
when "../route-reflector-client = 'false '";
Will allow you to turn of reflection if the node is a route reflector. 

My question is how does the 3 tier Route Reflection work?  Does it require you can reflect from a client? How does the 3 tier policy work.
