### ISSUE TITLE
replace-as option problematic?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#70]
It's unclear what feature replace-peer-as is intended to be.  Is this meant to cover as-override for VPNs?

      leaf replace-peer-as {
        type boolean;
        default "false";
        description
          "Replace occurrences of the peer's AS in the AS_PATH with
           the local autonomous system number";

**Comment by suehares** [comment]
Cisco: 
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-17/irg-xe-17-book/bgp-replace-ASNs.pdf

Is this linked to as-overide in Juniper: 
https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/as-override-edit-protocols-bgp.html

If these are two versions of the same feature, I think we have another defacto standard features, that should be codified by going through IDR/Grow discussions. 

 Could not easily find this feature in open config or FRR

**Comment by jhaas-pfrc** [comment]
> Cisco:
> https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/iproute_bgp/configuration/xe-17/irg-xe-17-book/bgp-replace-ASNs.pdf
> 
> Is this linked to as-overide in Juniper:
> https://www.juniper.net/documentation/us/en/software/junos/bgp/topics/ref/statement/as-override-edit-protocols-bgp.html
> 
> If these are two versions of the same feature, I think we have another defacto standard features, that should be codified by going through IDR/Grow discussions.
> 
> Could not easily find this feature in open config or FRR

The semantics of the quoted cisco replace-as are different than the one for as-override for Juniper.

In the IETF yang model cited in the original issue text, the configuration is boolean which isn't consistent with how the cisco version would work.  For Juniper, as-override is effectively a boolean.

I would suggest the proper action is for us to remove this configuration from the ietf model since it's under-specified and not a good match to more than one feature set.

**Comment by suehares** [comment]
agree to pull option.

**Comment by jhaas-pfrc** [comment]
I got confirmation from Rob Shakir that the intent in the OC model is Juniper's "as-override" feature.  That one is very common for support of l3vpn and similar protocols.

The question is whether we'd want to standardize this VPN specific feature in the core bgp model or figure out how every single BESS extension that needed it could get it?

It's perhaps an argument to leave it in the core model?

**Comment by jhaas-pfrc** [comment]
After further review, I believe we should leave this feature in the model.  It's common functionality required for BGP VPNs.  Multiple implementations have it as a feature at BGP neighbor scope of configuration.

To address the RFC documentation gap, I've started a new page in the BGP wiki to track these gaps.

https://trac.ietf.org/trac/idr/wiki/De%20facto%20BGP%20features%20needing%20documentation

If everyone agrees, I believe we can simply close this issue without further change.

**Comment by mjethanandani** [comment]
Should we document it more to make sure what is the intent, i.e. as-override feature for BGP VPN, and not to be confused with how Cisco has implemented it?

**Comment by jhaas-pfrc** [comment]
We have an interesting problem here: We typically want to refer back to RFC procedure for the behavior.  In this case, it doesn't exist.

What this leaves us in is a desire to discuss the feature in enough detail that you can figure it out without the rfc.  as-override is theoretically vendor syntax for doing this sort of thing.

That said, the fact that this overlaps another command with different semantics is problematic.  as-override exists in at least one cisco implementation (ios-xr) as well.

One option is to rename this to as-override given Rob's comment.

I'd like to hear Sue and Keyur's opinion about how to proceed on this one.

**Comment by mjethanandani** [comment]
as-override might be a clean way out of this.

**Comment by jhaas-pfrc** [comment]
After review, I think that while I'm familiar with this as "as-override", the semantics and the description in the leaf are clear.  Let's close this.
