### ISSUE TITLE
Keepalive configuration default problematic?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#72]
Consider:
    leaf keepalive {
      type uint16 {
        range "0..21845";
      }
      units "seconds";
      default "30";

The behavior in a number of implementations is to only have a holdtime configurable.  In such cases, if you configure the holdtime, the keepalive is automatically derived as 1/3 of holdtime.

I believe that in the presence of the default above, there's not a good way to enable that behavior.  The absence of configuration for keepalive in the presence of default implies 30.

I'd recommend removing the default, and noting the behavior we want in the description.

**Comment by jhaas-pfrc** [comment]
If we agree on the semantics of removing the default, the pull request will resolve it.

**Comment by suehares** [comment]
agree on sematics of removing the default.  RFC4771 says 30 seconds. 
We need to note that the removal reflects current usage.
