### ISSUE TITLE
remote-as vs peer-as?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#74]
We have two nodes containing the peer's AS number.

I suspect the intent is to have one be configuration state and the other (likely remote-as) be operational state.

If so, likely fix is:
- Rename remote-as as "received-remote-as"
- Make it config false

  grouping neighbor-group-config {
    description
      "Neighbor level configuration items.";
    leaf remote-as {
      type inet:as-number;
      description
        "The remote autonomous system number received in
         the BGP OPEN message.";
      reference
        "RFC 4271, Section 4.2.";
    }
    leaf peer-as {
      type inet:as-number;
      description
        "AS number of the peer.";
    }

**Comment by jhaas-pfrc** [comment]
Reviewing the code and the related openconfig model, remote-as seems redundant.  It should be deleted.

**Comment by suehares** [comment]
Does this remote-as receive interwork with the fake AS feature

remote note (AS2) but allows overide of AS7002 --->   received AS depends on which of the two AS sent.

**Comment by jhaas-pfrc** [comment]
> Does this remote-as receive interwork with the fake AS feature
> 
> remote note (AS2) but allows overide of AS7002 ---> received AS depends on which of the two AS sent.

I don't believe that's the intent of what's in the model we have, nor the one currently published by openconfig.

**Comment by jhaas-pfrc** [comment]
Updating my original comment, the remaining AS will be config true because this is how the AS number for the neighbor is configured.
