### ISSUE TITLE
Finalize remove-private-as behavior

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#75]
The text in the comment implies ambiguity about how we should proceed.  If the behavior is actually settled, we should remove the comment.

    leaf remove-private-as {
      // could also make this a container with a flag to enable
      // remove-private and separate option.  here, option implies
      // remove-private is enabled.
      type bt:remove-private-as-option;
      description
        "Remove private AS numbers from updates sent to peers - when
         this leaf is not specified, the AS_PATH attribute should be
         sent to the peer unchanged";
    }

**Comment by suehares** [comment]
Remove the comment let the description stand.
