### ISSUE TITLE
Flap damping type gauge32?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#76]
The type of configured route flap damping parameters is yang:gauge32.  I'm under the impression that this type is primarily intended for operational state.  If so, these should be uint32.

      leaf reach-decay {
        type yang:gauge32;
        units "seconds";
        default "300";
        description
          "This value specifies the time desired for the instability
           metric value to reach one-half of its current value when
           the route is reachable. This half-life value determines
           the rate at which the metric value is decayed. A smaller
           half-life value makes a suppressed route reusable sooner
           than a larger value.";
      }
      leaf unreach-decay {
        type yang:gauge32;
        units "seconds";
        default "900";
        description
          "This value acts the same as reach-decay except that it
           specifies the rate at which the instability metric is
           decayed when a route is unreachable. It should have a
           value greater than or equal to reach-decay.";
      }
      leaf keep-history {
        type yang:gauge32;

**Comment by suehares** [comment]
These gauge values were set as the initial gauge maximums.   Is this still the case.

**Comment by mjethanandani** [comment]
The definition of gauge32 is something we inherited in YANG from SMI. It is described as:

        "The gauge32 type represents a non-negative integer, which
         may increase or decrease, but shall never exceed a maximum
         value, nor fall below a minimum value.  The maximum value
         cannot be greater than 2^32-1 (4294967295 decimal), and
         the minimum value cannot be smaller than 0.  The value of
         a gauge32 has its maximum value whenever the information
         being modeled is greater than or equal to its maximum
         value, and has its minimum value whenever the information
         being modeled is smaller than or equal to its minimum value.
         If the information being modeled subsequently decreases
         below (increases above) the maximum (minimum) value, the
         gauge32 also decreases (increases).

I would not say that the type is limited to operational state. But if this is not the expected behavior, we can change it to uint32.

**Comment by jhaas-pfrc** [comment]
@mjethanandani 
> The definition of gauge32 is something we inherited in YANG from SMI. It is described as:
> 
> ```
>     "The gauge32 type represents a non-negative integer, which
>      may increase or decrease, but shall never exceed a maximum
>      value, nor fall below a minimum value.  The maximum value
>      cannot be greater than 2^32-1 (4294967295 decimal), and
>      the minimum value cannot be smaller than 0.  The value of
>      a gauge32 has its maximum value whenever the information
>      being modeled is greater than or equal to its maximum
>      value, and has its minimum value whenever the information
>      being modeled is smaller than or equal to its minimum value.
>      If the information being modeled subsequently decreases
>      below (increases above) the maximum (minimum) value, the
>      gauge32 also decreases (increases).
> ```
> 
> I would not say that the type is limited to operational state. But if this is not the expected behavior, we can change it to uint32.

Mostly, this sticks out.  While I have the context for how this was used in SMIv2, we're not regularly using this type in the bgp model.  If there's a stylistic reason to use this from other IETF work for configuration state, I'm fine leaving it.  But if there isn't, I'd suggest making the type change.

**Comment by mjethanandani** [comment]
> @mjethanandani
> 
> > The definition of gauge32 is something we inherited in YANG from SMI. It is described as:
> > ```
> >     "The gauge32 type represents a non-negative integer, which
> >      may increase or decrease, but shall never exceed a maximum
> >      value, nor fall below a minimum value.  The maximum value
> >      cannot be greater than 2^32-1 (4294967295 decimal), and
> >      the minimum value cannot be smaller than 0.  The value of
> >      a gauge32 has its maximum value whenever the information
> >      being modeled is greater than or equal to its maximum
> >      value, and has its minimum value whenever the information
> >      being modeled is smaller than or equal to its minimum value.
> >      If the information being modeled subsequently decreases
> >      below (increases above) the maximum (minimum) value, the
> >      gauge32 also decreases (increases).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would not say that the type is limited to operational state. But if this is not the expected behavior, we can change it to uint32.
> 
> Mostly, this sticks out. While I have the context for how this was used in SMIv2, we're not regularly using this type in the bgp model. If there's a stylistic reason to use this from other IETF work for configuration state, I'm fine leaving it. But if there isn't, I'd suggest making the type change.

Ok. Will change it to uint32.

**Comment by mjethanandani** [comment]
> @mjethanandani
> 
> > The definition of gauge32 is something we inherited in YANG from SMI. It is described as:
> > ```
> >     "The gauge32 type represents a non-negative integer, which
> >      may increase or decrease, but shall never exceed a maximum
> >      value, nor fall below a minimum value.  The maximum value
> >      cannot be greater than 2^32-1 (4294967295 decimal), and
> >      the minimum value cannot be smaller than 0.  The value of
> >      a gauge32 has its maximum value whenever the information
> >      being modeled is greater than or equal to its maximum
> >      value, and has its minimum value whenever the information
> >      being modeled is smaller than or equal to its minimum value.
> >      If the information being modeled subsequently decreases
> >      below (increases above) the maximum (minimum) value, the
> >      gauge32 also decreases (increases).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would not say that the type is limited to operational state. But if this is not the expected behavior, we can change it to uint32.
> 
> Mostly, this sticks out. While I have the context for how this was used in SMIv2, we're not regularly using this type in the bgp model. If there's a stylistic reason to use this from other IETF work for configuration state, I'm fine leaving it. But if there isn't, I'd suggest making the type change.

Ok. I will change it to uint32.
