### ISSUE TITLE
Suggest renaming auth-password to md5-auth-password

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#77]
I'd suggest renaming auth-password to md5-auth-password.  As we gain deployment experience with tcp-ao we may want this to be unambiguous.

    leaf auth-password {
      type string;
      description
        "Configures an MD5 authentication password for use with
         neighboring devices.";
      reference
        "RFC 2385: Protection of BGP Sessions via the TCP MD5
                   Signature Option.";

**Comment by suehares** [comment]
It should be renamed to md5-auth-password.
