### ISSUE TITLE
indexes are under specified for as-paths

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#78]
We have an as-path segment index, as noted below.

We do need an index to support more than one segment.  However, the index doesn't specify what we do here. 

Is the index a continuous range?  E.g. 1,2,3?  Is it zero based or one-based?  How do we ordering of the segments - is it left to right as in the AS-path and are they numbered 1,2,3 or 3,2,1?

  grouping bgp-as-path-attr {                                                                                
    description                                                                                              
      "Data for representing BGP AS-PATH attribute";                                                         
    leaf index {                                                                                             
      type uint16;                                                                                           
      description                                                                                            
        "An index into the AS segments.";                                                                    
    }

**Comment by jhaas-pfrc** [comment]
Comparing vs. openconfig model.  The index is unnecessary.  Yang list ordering semantics do not require the elements to be explicitly enumerated to allow them to be ordered.

**Comment by suehares** [comment]
I realize that Yang list ordering does not require enumeration. 
However, is the enumeration useful in implementations?   Keyur and Jeff should check.
