### ISSUE TITLE
extended communities in rib have problems

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#79]
1. The type is rt:route-target.  This needs to be far more generic.  See other issues about representations of extended communities.
2. Why is this in ietf-bgp-rib.yang rather than ietf-bgp-rib-attributes like other communities?

  grouping ext-community-attributes {
    description
      "A grouping for all external community parameters.";

    leaf-list ext-community {
      type rt:route-target;
      description
        "List of BGP extended community attributes. The received
         extended community may be an explicitly modeled
         type or unknown, represented by an 8-octet value
         formatted according to RFC 4360.";
      reference
        "RFC 4360 - BGP Extended Communities Attribute";
    }
  }

**Comment by suehares** [comment]
This is one of the issues that should be solved prior to release.
Can we tag these features with a label.

**Comment by mjethanandani** [comment]
In addition, the ext-community-sets definition in policy includes route-target as a member. This should be of bgp-ext-community-type.

```
          leaf-list member {
            type union {
              type rt-types:route-target;
              type bt:bgp-community-regexp-type;
            }
            description
              "Members of the extended community set.";
          }
```
