### ISSUE TITLE
transport config and security sessions have overlapping semantics and should be cleaned up

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#82]
grouping neighbor-group-transport-config includes things like md5-password

the neighbor secure-session container has some overlap

The parameters in the group-transport-config overlaps some of the neighbor parameters.

Work should be done to clean up these semantics.

**Comment by suehares** [comment]
Agree with Jeff that structure must clear up the overlap between neighbor-group-transport-config and 
neighbor secure-session.   

Where did overlap come from?
