### ISSUE TITLE
Clear action not sufficiently flexible

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#85]
We have the "bounce a session" action.  However, we don't have the usual "soft" options for causing route refreshes to be done.

        action clear {                                                                                      
          if-feature "bt:clear-neighbors";                                                                  
          description                                                                                       
            "Clear neighbors action.";

**Comment by jhaas-pfrc** [comment]
As I'm working through the possible changes for the input (needing to understand yang rules here), it's also occurred to me that the semantic of this as an "action" is an interesting behavior vs. deployed routers.

Actions are anchored vs. a given bit of state in the tree.  This means the only thing that makes sense for the action is clear (soft (in|out)) for THAT neighbor.

In pretty much every implementation I'm familiar with, the clear operation is a global rpc from yang's perspective.

While making this a global RPC rather than an action would address that, it will still have the same issues with the inputs.

**Comment by jhaas-pfrc** [comment]
Related observation: If we make the contents of clear into a grouping, vendors can provide a global version of the command in their implementations.  The current action format means that the additionally required arguments in global scope are implied by positioning in the tree.

**Comment by jhaas-pfrc** [comment]
Followup observation: While the arguments for the clear action could be made a grouping, the likeliest way that would be done is as a container.  That would add a additional token around the operation and would be unwelcome noise.

**Comment by mjethanandani** [comment]
> Related observation: If we make the contents of clear into a grouping, vendors can provide a global version of the command in their implementations.

The only problem with a grouping is that it cannot be augmented. The augmentation has to happen where the grouping is invoked using the 'uses' statement. If there are multiple locations where the grouping gets invoked, then the implementation has to decide whether they want to augment each of the locations.
