### ISSUE TITLE
BFD configuration

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#86]
Some implementations of BGP has their BFD configuration as an interface specific configuration.
Some, e.g. JunOS, has its BFD configuration as per-neighbor.

we should figure out how to be supportive of both.

**Comment by suehares** [comment]
+1 on supporting BFD per-neighbor.

**Comment by mjethanandani** [comment]
The BGP model only enables/disables an interface for BFD. The part of configuring which neighbor receives is part of BFD configuration, as far as I can see:

       +--rw ip-sh
          +--rw sessions
          |  +--rw session* [interface dest-addr]
          |     +--rw interface                         if:interface-ref
          |     +--rw dest-addr                         inet:ip-address
          |     +--rw source-addr?                      inet:ip-address
          |     +--rw local-multiplier?                 multiplier

**Comment by jhaas-pfrc** [comment]
I'll be proposing a patch maybe next week.
