### ISSUE TITLE
clear routes isn't clear?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#87]
What feature is clear routes intended to cover?  The documentation doesn't have enough detail.

  grouping clear-routes {
    description
      "Action to clear BGP routes.";
    container clear-routes {
      if-feature "bt:clear-routes";
      action clear {

**Comment by suehares** [comment]
Is this clearing AS path and leaving prefix in-active or is it removing the entire rout.

**Comment by mjethanandani** [comment]
At least one implementation does a 'clear ip bgp route *', and it clears rib-in.
