### ISSUE TITLE
module ietf-bgp-command rename?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#88]
module ietf-bgp-command is there to help flatten the routing tables for CLI and similar outputs.  It probably needs a better name, and minimally the module needs a description as to what it's for.

**Comment by suehares** [comment]
+1 - recall our discussion on what command is there for.   Is there common name for those using CLI.

**Comment by mjethanandani** [comment]
ietf-bgp-command model is not part of this draft, and I should ideally remove it from the repository. We will create a new draft to address how CLI can support this model.
