### ISSUE TITLE
ext-community-sets have previously referenced issues with types

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#89]
rt-types:route-target is problem as a generic bit of extended-community policy.

      container ext-community-sets {
        description
          "Enclosing container for list of extended BGP community
           sets";
        list ext-community-set {
          key "name";
          description
            "List of defined extended BGP community sets";
          leaf name {
            type string;
            description
              "Name / label of the extended community set -- this is
               used to reference the set in match conditions";
          }
          leaf-list member {
            type union {
              type rt-types:route-target;
              type bt:bgp-community-regexp-type;
            }

**Comment by suehares** [comment]
Are type type sizes the same in the leaf-list member?  What hapens if they are not the same size.l 

     leaf-list member {
        type union {
          type rt-types:route-target;
          type bt:bgp-community-regexp-type;
        }

**Comment by jhaas-pfrc** [comment]
The underlying issue is that in RFC 8294 that route-targets don't use any usable key words.  It's types 0,1,2,6 with presumed subtype of 2, with value specific to the type/sub-type.
Problem in addition to being hard to use, how do extend for the new types?  The module in RFC 8294 is not IANA maintained and is therefore hard to do.
Second problem is that even if it's maintainable, how does match intend to work vs. the generated extended community?  The route-target type may not be a string-compatible match for arbitrary communities.

**Comment by suehares** [comment]
While walking through open issues, it appears we have a maintaince issue here.  
1.  Is 8294 going to be revised for usable key words or IANA issues? 
2.  Can we use the approach of string (human readable) and a canonical format we have used elsewhere?

**Comment by jhaas-pfrc** [comment]
> While walking through open issues, it appears we have a maintaince issue here.
> 
>     1. Is 8294 going to be revised for usable key words or IANA issues?

I filed an errata on the erroneous type-6 route distinguisher.

I've taken no action on trying to deal with the keywords for those types otherwise.  BGP's needs at the protocol level will be different than the use cases solely in the VPN service model contexts.  We'll likely figure that stuff out as part of doing VPN model interwork evaluation.  Feel free to use the l3vpn model that I've not really looked at in ages for evaluation purposes:

https://datatracker.ietf.org/doc/html/draft-ietf-bess-l3vpn-yang

>     2. Can we use the approach of string (human readable) and a canonical format we have used elsewhere?

That's largely what we've done in our models for extended communities.  The issue are the "typed" elements in things like 8294 that have no keywords to do the job outside of their specific context.  Under the covers, the base type remains "string".  YANG type strictness is a challenge here.

**Comment by mjethanandani** [comment]
As far as this model is concerned, this issue is addressed. We removed the definition of type rt-types:route-target and replaced it with our definition.

This item was left open as the existing definition is problematic for the L3VPN model.
