### ISSUE TITLE
as-path-sets' members are a string

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#90]
The members of the set are done as strings.  This might be fine, however the inputs are "match any" and "match all".  So they ideally should be a leaflist of ASes so we don't have to worry about parsing the individual ASes from the string.

      container as-path-sets {
        description 
          "Enclosing container for list of define AS path sets";                                            
        list as-path-set {                                                                                  
          key "name"; 
          description
            "List of defined AS path sets";                                                                 
          leaf name {
            type string;                                                                                    
            description
              "Name of the AS path set -- this is used to reference the                                     
               set in match conditions";                                                                    
          } 
          leaf-list member {
            type string;                                                                                    
            description                                                                                     
              "AS path expression -- list of ASes in the set";                                              
          }

**Comment by suehares** [comment]
+ 1 pm leaf-list of AS

**Comment by mjethanandani** [comment]
From Yingzhen:

list as-path-prepend {
<           key "asn";
<           description
<             "List of AS numbers to prepend.";
<           leaf repeat-n {
<             type uint8 {
<               range "1..max";
<             }
<             description
<               "Number of times to prepend the AS number to the AS
<                path. The value should be between 1 and the maximum
<                supported by the implementation.";
<           }
<           leaf asn {
<             type inet:as-number;
<             description
<               "AS number to prepend to the AS path. If not specified,
<                then the local AS number will be used for prepending.";

**Comment by jhaas-pfrc** [comment]
The as-path-set was intended to carry regular expressions, although that wasn't clear earlier.  This is an incorrect issue and will be closed.
