### ISSUE TITLE
No  aspath regex?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#91]
BGP as-path regular expressions are a critical feature for matching BGP routes.  We don't have anything that implements that.

The community regex is a pattern worth examining.

Note that this is very vendor specific and could be generically problematic...

**Comment by suehares** [comment]
The earlier discussion on the BGP as-path regex left it as a string.   The as-path regular expression is very specific to a vendor.  Any suggestions from Keyur would be useful.

**Comment by jhaas-pfrc** [comment]
as-path-sets are intended to cover this situation.
However, it's not clear what behavior we want for the regular expression to match on.
This behavior will be per-vendor implementation, which creates interoperability issues.

**Comment by jhaas-pfrc** [comment]
Closing this issue since regular expressions are supported, but aren't normalized.  A new issue will be opened to track that.
