### ISSUE TITLE
MAINTENANCE - What does supporting additional address families look like?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#92]
We have some generic support for other address families.  We have capability negotiation components.  But what does it look like to augment things like rib?

We should have an example.

**Comment by mjethanandani** [comment]
Here is an example of how an augmentation of the rib portion of the module would look like for adding a new address family.

  augment /rt:routing/rt:control-plane-protocols/rt:control-plane-protocol/bgp:bgp/bgp:rib/bgp:afi-safis/bgp:afi-safi:
    +--ro foo
       +--ro blah?   string

And here is the model.

[example-new-addr-family.yang.zip](https://github.com/mjethanandani/ietf-bgp-yang/files/6722928/example-new-addr-family.yang.zip)

**Comment by mjethanandani** [comment]
It turns out there is already an example in the draft on how to augment the model to add an AFI. Closing this issue.

**Comment by mjethanandani** [comment]
Reopened to use for the PR on enhancing the new AFI example.

**Comment by mjethanandani** [comment]
Published the draft with the enhanced example. The example not only shows the rib/route part of the model can be augmented, but also proved that the current set of groupings can be reused to add a new address family.
