### ISSUE TITLE
Multiple bgp instances?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#94]
How do we do an instance of BGP in the "core" instance.
How do we do a separate instance for CE connections?
See IDR discussion.

**Comment by mjethanandani** [comment]
Is there a link to the IDR discussion that you can share here?

But in general, we are augmenting ietf-routing module, which carries a list of 'control-plane-protocol'. Therefore, one can create an instance of BGP for the "core" and another instance (with a different name) for CE connections.

**Comment by jhaas-pfrc** [comment]
@mjethanandani 
> Is there a link to the IDR discussion that you can share here?
> 
> But in general, we are augmenting ietf-routing module, which carries a list of 'control-plane-protocol'. Therefore, one can create an instance of BGP for the "core" and another instance (with a different name) for CE connections.

Start here:
https://mailarchive.ietf.org/arch/msg/idr/7SUlaFmoti5eg9Msvhriv3tNFMg

**Comment by mjethanandani** [comment]
I think example-bgp-configuration-a.1.4.xml has an example that kind of answers the question. The assumption of course is that there is one VRF instance, and within that instance one can have one or more BGP instances.

**Comment by mjethanandani** [comment]
In trying to create another example configuration based on the configuration shared by Wanghaibo, I noticed that we do not currently track a neighbor's AS number. This is what the tree looks like for that portion of the configuration. How important is to know the neighbor AS number?

       +--rw neighbors
       |  +--rw neighbor* [remote-address]
       |  |  +--ro local-address?                              inet:ip-address
       |  |  +--ro local-port?                                 inet:port-number
       |  |  +--rw remote-address                              inet:ip-address
       |  |  +--ro remote-port?                                inet:port-number
       |  |  +--ro peer-type?                                  bt:peer-type
       |  |  +--rw peer-group?                                 -> ../../../peer-groups/peer-group/peer-group-name
       |  |  +--ro identifier?                                 yang:dotted-quad
       |  |  +--rw enabled?                                    boolean
       |  |  +--rw secure-session-enable?                      boolean
       |  |  +--rw secure-session
       |  |  |  +--rw (option)?
       |  |  |     +--:(ao)
       |  |  |     |  +---u tcp:ao
       |  |  |     |  +--rw ao-keychain?   kc:key-chain-ref
       |  |  |     +--:(md5)
       |  |  |     |  +---u tcp:md5
       |  |  |     |  +--rw md5-keychain?   kc:key-chain-ref
       |  |  |     +--:(ipsec)
       |  |  |        +--rw sa?   string

**Comment by mjethanandani** [comment]
Attached is the example XML configuration for what Wangbaiho shared. Included is the configuration he wanted to see supported. Note, I replaced VPN with ipv6-unicast, as this model does not support any VPN type, and also because that is not the point being made here as far as VRF support is concerned. Also, I dropped any RD configuration, as this model does not support configuration of RD.

[example-bgp-configuration-a.1.5.xml.zip](https://github.com/mjethanandani/ietf-bgp-yang/files/6712727/example-bgp-configuration-a.1.5.xml.zip)

    router bgp 100 instance a1       // one bgp instance here
     bgp router-id 12.12.12.12
     address-family vpnv4 unicast
     !
     neighbor 121.1.1.1
      remote-as 100
      address-family vpnv4 unicast   //and its vpnv4 unicast neighbor, support service for vrf-a1
      !
     !
     vrf vrf-a1                    //vrf-a1 here
      rd auto
      address-family ipv4 unicast
       redistribute static
      !
     !
    !
    router bgp 200 instance a2      // another bgp instance here
     bgp router-id 13.1.1.1
     address-family vpnv4 unicast
     !
     address-family ipv6 unicast
     !
     address-family l2vpn evpn
     !
     neighbor 122.1.1.1
      remote-as 100
      address-family vpnv4 unicast  //and its vpnv4 unicast neighbor，support service for a3
      !
      address-family l2vpn evpn
      !
     !
     vrf a3                     //a3 here
      rd 13.1.1.1:2<http://13.1.1.1:2>
      address-family ipv4 unicast
      !
     !

**Comment by jhaas-pfrc** [comment]
Note that this question overlaps why we have "interfaces" in the bgp container, which is per-network-instance.
