### ISSUE TITLE
MAINTENANCE - How to maintain extended-community datatype?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#96]
Stub issue to decide whether we have enough plumbing to maintain datatypes that will change regularly, such as extended communities.

**Comment by suehares** [comment]
This is a major concern.  The only way I can see this going forward is to make sure the stubs point to inclusions files that IANA manages.  No other ideas.

**Comment by mjethanandani** [comment]
Agree that there is no easy way to augment extended-community definition as they exist today. Unless there is another way to define the extended-community, i.e. other than them being typedefs, we should ack the issue and close it.

**Comment by jhaas-pfrc** [comment]
> Agree that there is no easy way to augment extended-community definition as they exist today. Unless there is another way to define the extended-community, i.e. other than them being typedefs, we should ack the issue and close it.

My suggestion is don't close this without some sort of appropriate action.  An example of such an action would be a "maintenance" section in the internet-draft that says what we'll be doing to maintain it.  

I suspect of the work will be to publish it as a separate iana maintained module.  The draft containing the module will have to have a maintenance policy.

This means we have file work to do.

**Comment by mjethanandani** [comment]
Move the typedefs for extended communities out of the existing module into a new iana-bgp-types.

**Comment by mjethanandani** [comment]
We will discuss this issue today. While the YANG language does not allow for a typedef to be augmented, it can be updated. To reduce the friction on the update, one option is to move the ietf-bgp-types module to be a IANA maintained module - iana-bgp-type.
