### ISSUE TITLE
MAINTENANCE - How to maintain attr-set attributes?

### ISSUE THREAD

**Issue by jhaas-pfrc** [mjethanandani/ietf-bgp-yang#97]
BGP periodically adds new path attributes as part of maintaining the feature.

Currently, it is defined as a grouping.

What is the maintenance procedure to update that grouping?

**Comment by mjethanandani** [comment]
@jhaas-pfrc, I am not sure if this is the exact example you are looking for, but here is an example of how a new attr-set attribute can be added to the model as an augmentation. Let me know if this addresses this issue.

augment /rt:routing/rt:control-plane-protocols/rt:control-plane-protocol/bgp:bgp/bgp:rib/bgp:attr-sets/bgp:attr-set/bgp:attr-set-attributes:
    +--ro foo
       +--ro blah?   boolean

where 'blah' is the new attr-set-attribute that I have added to the model. Attached is the example YANG model.

[example-new-attr-set-bgp.yang.zip](https://github.com/mjethanandani/ietf-bgp-yang/files/6722735/example-new-attr-set-bgp.yang.zip)

**Comment by jhaas-pfrc** [comment]
We can augment the places where attr-set-attributes are being used as Mahesh notes above.  However, since it's a grouping, it'll be necessary to replicate those changes each of such places.  

In the current RFC to be text, this is used in exactly one places.  The example flattened rib module, however, has more impact on it.  Since that flattened "bgp commands" module won't be going into the RFC, that's ok.
